spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/example
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      connection-test-query: select 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
#    cluster:
#      nodes:
#        - 127.0.0.1:6379
#    jedis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
mybatis:
  type-aliases-package: org.charlie.example
  mapper-locations: classpath:mapper/mysql/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: true
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      zone: chengdu
    hostname: 127.0.0.1
    prefer-ip-address: false
    health-check-url-path: /health
    ip-address: 127.0.0.1


feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000 # unit: ms
        readTimeout: 2000 # unit: ms
        loggerLevel: full # 日志级别
        errorDecoder: org.charlie.example.framework.configs.io.feign.ExampleErrorDecoder
#        retryer: org.charlie.example.framework.configs.io.feign.DefaultFeignConfiguration
        requestInterceptors:
          - org.charlie.example.framework.interceptors.out.feign.GlobalTraceIdRequestInterceptor
        decode404: false
#        encode: com.example.SimpleEncoder
#        decoder: com.example.SimpleDecoder
#        contract: com.example.SimpleContract
  hystrix:
    enabled: true

  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

# application configure
example: # FIXME: replace config name here
  thread:
    count: 10
    max-count: 100
  http:
    retry: 0
    keep-alive-ms: 60000 # unit: ms
    pool-max-connections: 100
    default-pool-connections-per-route: 100
    connection-timeout-ms: 500
    request-timeout-ms: 500 # unit: ms
    socket-timeout-ms: 1000 # unit: ms
    connections-per-route:
      - url: http://127.0.0.1:8101/example
        connections: 100
  redis-key-prefix: EXAMPLE_

