spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/foo
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      connection-test-query: select 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis: #lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
mybatis:
  type-aliases-package: org.charlie.template
  mapper-locations: classpath:mapper/mysql/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

template:
  thread-num: 10