spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8101
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    max-connections: 100
  servlet:
    context-path: /template
#dubbo:
#  scan:
#    base-packages: org.apache.dubbo.spring.boot.sample.provider.service
#  protocol:
#    name: dubbo-demo
#    port: 12345
#  registry:
#    address: N/A