spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: on
      force: on
server:
  port: 8101
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    max-connections: 100
  servlet:
    context-path: /foo
