server:
  port: 8101
eureka:
  client:
    register-with-eureka: false #是否将自己注册到eureka服务端上去
    fetch-registry: false #是否获取eureka服务端上注册的服务列表
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: false # 启用eureka客户端
    registry-fetch-interval-seconds: 30 #定义去eureka服务端获取服务列表的时间间隔
  instance: #eureka客户端实例配置
    lease-renewal-interval-in-seconds: 30 #定义服务多久去注册中心续约
    lease-expiration-duration-in-seconds: 90 #定义服务多久不去续约认为服务失效
    metadata-map:
      zone: chengdu #所在区域
    hostname: localhost #服务主机名称
    prefer-ip-address: false #是否优先使用ip来作为主机名

spring:
  cloud:
    inetutils:
      preferred-networks: 127.0.
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 10
        one-indexed-parameters: false
        max-page-size: 2000
        prefix:
        qualifier-delimiter: _
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/foo
      username: root
      password: root
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 6000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis: #lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  kafka:
    producer:
#      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      enable-auto-commit: true
#      group-id: applog
#      auto-offset-reset: latest
#      bootstrap-servers: 127.0.0.1:9092
mybatis:
  type-aliases-package: org.charlie.template
  mapper-locations: classpath:mapper/mysql/*.xml
  configuration:
    map-underscore-to-camel-case: true
foo:
  redis-key-prefix: foo

es:
  urls: 127.0.0.1:9200