spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCLCDB
    username: root
    password: 123123
    hikari:
      pool-name: MyHikariCP
      minimum-idle: 5
      maximum-pool-size: 1000
      connection-timeout: 30000
      max-lifetime: 45000
      connection-test-query: SELECT 1