CREATE TABLE FOO (
    FOO_INT INTEGER NOT NULL,
    FOO_STR VARCHAR2(8),
    FOO_DATE TIMESTAMP(6),
    FOO_INT_FK INTEGER
);

ALTER TABLE FOO ADD PRIMARY KEY(FOO_INT);

CREATE TABLE BAR (
    BAR_INT INTEGER NOT NULL,
    FOO_INT INTEGER
);

ALTER TABLE BAR ADD PRIMARY KEY(BAR_INT);